# 7월 아이스크림 총 주문량 + 상반기 아이스크림 총 주문량 큰 순서대로 LIMIT 3

SELECT H.FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC    
    ) H
LEFT JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
    ORDER BY TOTAL_ORDER DESC
    ) J
ON H.FLAVOR = J.FLAVOR
ORDER BY H.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3

