SELECT P.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R
ON P.MEMBER_ID = R.MEMBER_ID
WHERE P.MEMBER_ID = (
    SELECT P.MEMBER_ID
    FROM MEMBER_PROFILE P
    JOIN REST_REVIEW R
    ON P.MEMBER_ID = R.MEMBER_ID
    GROUP BY P.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT